### ISSUE TITLE
i am back for the funny

### ISSUE THREAD

**Issue by ghost** [jpepperoni/quiznos2#2]
The

**Comment by ghost** [comment]
joesepj pepper leon put source code on github NOW

**Comment by joey5802** [comment]
> joesepj pepper leon put source code on github NOW

Hi Nick,
no
Sincerely,
Joey Pepper Leon

**Comment by ghost** [comment]
> > joesepj pepper leon put source code on github NOW
> 
> 
> 
> Hi Nick,
> 
> no
> 
> Sincerely,
> 
> Joey Pepper Leon

poopy poo head
